! =================================================!
! ANSYS APDL-scripts - Verification
!    -----------------------------------------
!       Geometry: [m]
!       Force:    [N]
!       Moment:   [Nm]
!       Pressure: [Pa]
! =================================================!

FINISH		 ! Make sure current ANSYS module is closed
/CLEAR,START ! Clear the ANSYS workspace 

! White background
/RGB,INDEX,100,100,100, 0   
/RGB,INDEX, 80, 80, 80,13   
/RGB,INDEX, 60, 60, 60,14   
/RGB,INDEX, 0, 0, 0,15  

! =================================================!
! INPUT DATA - including material
! =================================================!

PI = 4*ATAN(1.0) ! Define variable PI as 3.1415...

! Remember to update title
*dim,TITLE_TEXT,string,20 ! Maximum 20 characters
/TITLE,%TITLE_TEXT(1)% ADPL verification of composit bone

!Young and Poission
YOUNG_COMPACT = 19e9
POISSON_COMPACT = 0.4

YOUNG_SPONGY = 10e9
POISSON_SPONGY = 0.2

YOUNG_MARROW = 5e9  !Ændret lidt for at simplificere
POISSON_MARROW = 0.3

TIMO = 1000*YOUNG_COMPACT

TH = 0.035 !Thickness

!Max Stress on beam
M=30.34963218
I=(1/12)*TH**4
h=0.0175
sigmamax=(M/I)*(TH/2)

! =================================================!
! GEOMETRY DEFINITIONS - in preprocessor (/PREP7)
! =================================================!
/PREP7 ! Enter the preprocessor

!Keypoints
K,1,0,0,0
K,2,0.008,0,0
K,3,0.013,0,0
K,4,0.022,0,0
K,5,0.027,0,0
K,6,0.035,0,0
K,7,0,0.4225,0
K,8,0.008,0.4225,0
K,9,0.013,0.4225,0
K,10,0.022,0.4225,0
K,11,0.027,0.4225,0
K,12,0.035,0.4225,0

!Lines
L,1,2
L,2,8
L,8,7
L,7,1
L,2,3
L,3,9
L,9,8
L,3,4
L,4,10
L,10,9
L,4,5
L,5,11
L,11,10
L,5,6
L,6,12
L,12,11

!Area from lines
AL,1,2,3,4
AL,5,6,7,2
AL,8,9,10,6
AL,11,12,13,9
AL,14,15,16,12

! =================================================!
! MATERIAL DEFINITIONS
! =================================================! 

MP,EX,1,YOUNG_COMPACT
MP,PRXY,1,POISSON_COMPACT
MP,EX,2,YOUNG_SPONGY
MP,PRXY,2,POISSON_SPONGY
MP,EX,3,YOUNG_MARROW
MP,PRXY,3,POISSON_MARROW

! =================================================!
! ELEMENT DEFINITIONS AND MESHING
! =================================================!

NodeSize = 0.005

!Compact
ET,1,PLANE183
KEYOPT,1,1,0
KEYOPT,1,3,3    !de er fint til at bevise - Da det bare er C-mtricen er der vendt?? i forhold til Plane strain, der bliver brugt i den rigtige model
R,1,TH
TYPE,1
MAT,1
AESIZE,1,NodeSize
MSHAPE,0,2D
MSHKEY,1
AMESH,1

ET,1,PLANE183
KEYOPT,1,1,0
KEYOPT,1,3,3	
R,1,TH
TYPE,1
MAT,1
AESIZE,5,NodeSize
MSHAPE,0,2D
MSHKEY,1
AMESH,5

!Spongy
ET,1,PLANE183
KEYOPT,1,1,0
KEYOPT,1,3,3	
R,1,TH
TYPE,1
MAT,2
AESIZE,2,NodeSize
MSHAPE,0,2D
MSHKEY,1
AMESH,2

ET,1,PLANE183
KEYOPT,1,1,0
KEYOPT,1,3,3	
R,1,TH
TYPE,1
MAT,2
AESIZE,4,NodeSize
MSHAPE,0,2D
MSHKEY,1
AMESH,4

!Marrow
ET,1,PLANE183
KEYOPT,1,1,0
KEYOPT,1,3,3
R,1,TH
TYPE,1
MAT,3
AESIZE,3,NodeSize
MSHAPE,0,2D
MSHKEY,1
AMESH,3


! =================================================!
! DEFINE BOUNDARY CONDITIONS AND LOADS
! =================================================! 

!Clamped
NSEL,S,LOC,Y,0
D,ALL,,,,,,ALL
NSEL,ALL

!Force
SELTOL,1E-6
NSEL,S,LOC,Y,0.4225
NSEL,R,LOC,X,0
F,ALL,FX,72.66

!Moments pressure
F,ALL,FY,-M/TH
NSEL,ALL
NSEL,S,LOC,Y,0.4225
NSEL,R,LOC,X,TH
F,ALL,FY,M/TH
NSEL,ALL

FINISH! Exit the preprocessor

! =================================================!
! SOLUTION - in solution (/SOL)
! =================================================!

/SOL	! Enter the solution module
SOLVE	! Obtain solution

FINISH	! Exit the solution module

! =================================================!
! STUDY RESULTS - in postprocessor (/POST1) 
! =================================================!

!Plane Stress plot in x direction
/POST1
SET,FIRST
PLDISP,2
