FINISH
/CLEAR,start


! =================================================!
! Setting up for Loop
! =================================================!
Start = 1	! Increment
End  = 10	! End of increment
!nincr = end - start
!*dim,MeshLengths,table,nincr,1,1

! Make incremental loop
*DO,DIV,Start,End,1

! Variables

meshx=10/(1.15**DIV)



!================================================
!
!
!Run some code here
!
*USE,'C:\Users\Victor\Documents\DTU\41812 FEA\Project 2\Github\FEA-Bone-1\Loopin louie (Element size testing)\TestMacro.mac',meshx
!
!================================================


!============
! Printing
!============


FILENAME = 'testFile'           ! Fil Navn - Husk at slette sidste ananlyse med samme navn

*cfopen,FILENAME,txt,,APPEND    !Smider en ny linje i text filen

*vwrite,meshx,Maxdisp           ! Skriver de forskellige data
(2(E15.6))                          ! Formattere data. Don't at me

*cfclose                        ! Lukker den text fil

/CLEAR,START ! Clear the ANSYS workspace
*ENDDO !End Loop