FINISH
/CLEAR,start


! =================================================!
! Setting up for Loop
! =================================================!
Start = 1	! Increment
End  = 100	! End of increment
!nincr = end - start
!*dim,MeshLengths,table,nincr,1,1

! Make incremental loop
*DO,DIV,Start,End,1

! Variables

meshx= 10.5 - DIV/10

/NERR,0

!================================================
!
!
!Run some code here
!
*USE,'C:\Users\s204414\Desktop\Bone day 7\Composite w hip cartilage.mac',meshx
!
!================================================


!============
! Printing
!============

/IMAGE,SAVE,CHRVAL(DIV),PNG

FILENAME = 'testFile'           ! Fil Navn - Husk at slette sidste ananlyse med samme navn

*cfopen,FILENAME,txt,,APPEND    !Smider en ny linje i text filen

*vwrite,meshx,Maxstress           ! Skriver de forskellige data
(2(E15.6))                          ! Formattere data. Don't at me

*cfclose                        ! Lukker den text fil

/CLEAR,START ! Clear the ANSYS workspace
*ENDDO !End Loop
