FINISH
/CLEAR,start


! =================================================!
! Setting up for Loop
! =================================================!
Start = 1	! Increment
End  = 100	! End of increment

! Make incremental loop
*DO,DIV,Start,End,1

! Variables
MINIMPACT=100 !N
PEAK=20000 !N
IMPACT=(19900/99)*DIV-(10000/99)

/NERR,0

!================================================
!
!
!Run some code here
!
*USE,'C:\Users\s204414\Desktop\Bone day 9\Composite impact only.mac',IMPACT
!
!================================================


!============
! Printing
!============

/IMAGE,SAVE,CHRVAL(DIV),PNG

FILENAME = 'testFile'           ! Fil Navn - Husk at slette sidste ananlyse med samme navn

*cfopen,FILENAME,txt,,APPEND    !Smider en ny linje i text filen

*vwrite,IMPACT,Maxstress           ! Skriver de forskellige data
(2(E15.6))                          ! Formattere data. Don't at me

*cfclose                        ! Lukker den text fil

/CLEAR,START ! Clear the ANSYS workspace
*ENDDO !End Loop